### ISSUE TITLE
Add ZHC

### ISSUE THREAD

**Issue by Sonic47** [TaskForce47/TF47-client-mod#11]
Wunsch von @Desty84 
https://github.com/TMZulu/ZHC

**Comment by NeutraleNull** [comment]
Öhm was spricht dagegen einfach die Mod zu laden? https://steamcommunity.com/sharedfiles/filedetails/?id=2450921295

**Comment by NeutraleNull** [comment]
Für einen Workshop reupload brauchen wir nämlich auch die permissions vom Autor
