### ISSUE TITLE
Door Wedge

### ISSUE THREAD

**Issue by JjUust** [TaskForce47/TF47-client-mod#41]
Braucht zu wenig Platz im Inventor / oder ein anderes Bild wird benötig 

So ein Unterlegkeil braucht ein bisschen mehr Platz und Gewicht

"AMP_Door_Wedge"

**Comment by DeRampage** [comment]
Wtf. Wie stellst du dir bitte nen Türstopper vor?

Aber feel free und mach ein neues Model.

**Comment by JjUust** [comment]
Kurz gesagt gib dem Ding einfach ein neues Bild im Arsenal. Mit dem was es dir aktuell zeigt kann du nen ganzen LKW stoppen
