### ISSUE TITLE
Mann kann das Tow Rope nicht fallen lassen

### ISSUE THREAD

**Issue by JjUust** [TaskForce47/TF47-client-mod#46]

**Comment by DeRampage** [comment]
bekannt. Gruppe Adler hat was verbockt

**Comment by Desty84** [comment]
Klaut der Mods und macht @DerZade verantwortlich? 🗡️ :D

**Comment by DerZade** [comment]
Bitte was? Warum haben wir das verbockt?

**Comment by DeRampage** [comment]
Euer Typ hat die Actions zu Ace Actions gemacht und nun finden ein paar sachen nicht mehr

**Comment by DerZade** [comment]
I second @Desty84

**Comment by nomisum** [comment]
das is mein kopierschutz

**Comment by nomisum** [comment]
ist im master gefixt (hatte es davor nur in einem weiteren internen fork gefixt)

**Comment by Desty84** [comment]
Vielen Dank @nomisum & @DerZade :D
