### ISSUE TITLE
TF MAAWS Buggy auf Public

### ISSUE THREAD

**Issue by ray-boop** [TaskForce47/TF47-client-mod#58]
Anscheinend sollen die HEAT Rounds keinen Schaden an Farhzeugen machen.
Im editor funktionierts, meistens.

**Comment by ray-boop** [comment]
ADM - Macht DMG an HMV
HEDP - Kein DMG an HMV + M113
MT - Minimal DMG an HMV + M113 (5%)
HEAT + RS - Kein DMG an HMV, BMDs / 1% DMG an Warrior / Nuked M113
HEAT TD - 10% DMG an HMV / Kein DMG an Warrior, BMDs, T-80s
SMOKE - Riesige Explosion aber kein Smoke, dafür 2% DMG am Warrior
ILLUM - eeeh fliegt ca 20 meter und zündet dann, aber immerhin kein Fahrzeug DMG

Wurde auf Pub mit RAWS getestet.

Witzigerweise Nuked die Tandem im Editor ziemlich gut.

**Comment by Desty84** [comment]
Darum meinte ich, lasst die RHS M3 drinnen....

**Comment by ray-boop** [comment]
Mir wurd nur mun mitgeteilt xD

Patch nachher.

**Comment by Desty84** [comment]
Aktuelle Branch testen.
RHS Ammo hat aufm penetrator TimetoLive = 0.001 aka der penetrator despawned bevor er das Fahrzeug trifft....deren Ammo kann gar net funktionieren the fuck?
